blog/urls.py
from django.urls import path
from blog.views import PostListView, PostDetailView, CategoryListView, TagListView, CategoryPostView, TagPostView

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name ='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name = 'tag_post'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from markdownx.models import MarkdownxField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 



class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = MarkdownxField('本文', help_text='Markdown形式で書いてください')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default = False)
    
    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title    
    
class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

blog/views.py
from django.shortcuts import render
from blog.models import Post,Category,Tag
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
# Create your views here.

class PostListView(ListView):
    # 下記はqueryset = Post.objects.allと一緒
    model = Post
    template_name = 'blog/index.html'

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj
    
class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts = Count('post', filter=Q(post__is_public=True))
    )

class TagListView(ListView):
    queryset = Tag.objects.annotate(
        num_posts = Count('post', filter=Q(post__is_public=True))
    )

class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context
    
class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context
    
    

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MyGadgetBlog{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/base/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ytaroのgadget</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

blog/templates/blog/category_list.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 

{% for category in object_list %}
<li>
  {{category.name}}<a href="{% url 'blog:category_post' category.slug %}">({{category.num_posts}})</a>
</li>
{% empty %}
<li>カテゴリはありません。</li>
{% endfor %} 
{% endblock %}

blog/templates/blog/category_post.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}
<div class="container">
    <h1>「{{category.name}}」の投稿一覧</h1>
    {% for post in object_list %}
    {% if user.is_authenticated or post.is_public %}
    <!-- Main Content-->
    <div class="card mb-3">
        {% if post.is_public %}
        <!-- <img src="..." class="card-img-top" alt="..."> -->
        <div class="card-body">
            <h5 class="card-title"><a href="{% url  'blog:post_detail' post.id %}">{{ post.title }}</a></h5>
            <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at|date}}</small></p>

            <p class="post-meta">
                Posted by
                <a href="/admin">{{user.username}}</a>
                on {{ post.published_at }}
            </p>
            <p class="post-meta">
                <small>カテゴリー：{{ post.category.name }}</small>
            </p>
            <p class="post-meta"><small>タグ:{% for tag in post.tags.all %}
                    {{tag.name}}
                    {% endfor %}
                </small></p>

        </div>
        {% endif %}
    </div>

    {% endif %}
    {% empty %}
    <p>まだ投稿がありません</p>
    {% endfor %}


</div>

 {% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}投稿一覧 | {{block.super}}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container" >
    <div class="row">
        <main class="col-md-7">
            <h1 class="mb-4">投稿一覧</h1>
            {% include 'blog/snippets/main_post_list.html' %}
        </main>
        <aside class="col-md-4 mb-10" >
            {% include 'blog/snippets/sidebar.html' %}
        </aside>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load app %}


{% block content %}
<div class="container">
    <div class="row mt-3">
    <h2>{{object.title}}</h2>
    <p>投稿日時：{{ object.published_at |date }}</p>
    <p>更新日時：{{object.updated_at |date}}</p>
    <p>カテゴリー：<a href="{% url 'blog:category_post' object.category.slug %}">{{object.category.name}}</a></p>
    <p>タグ：{% for tag in object.tags.all %}
    <a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }}</a>
    {% endfor %}</p>
    <hr>
    </div>
    <div class="row">
        <p>{{object.content|markdown_to_html}}</p>
    </div>
</div>
{% endblock %}
    

blog/templates/blog/snippets/main_post_list.html
{% for post in object_list %}
{% if user.is_authenticated or post.is_public %}
    <!-- Main Content-->
    <div class="card mb-3">
        {% if post.is_public %}
        <!-- 画像の表示設定 -->
        {% if post.image %}
        <a href="{% url 'blog:post_detail' post.id %}">
            <img src="{{post.image.url}}" class="card-img-top" alt="{{post.title}}" object-fit="none">
        </a>
        {% endif %} 
        <div class="card-body">
            <h5 class="card-title"><a href="{% url  'blog:post_detail' post.id %}">{{ post.title }}</a></h5>
            <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at|date}}</small></p>

            <p class="post-meta">
            Posted by
            <a href="/admin">{{user.username}}</a>
            on {{ post.published_at }}
            </p>
            <p class="post-meta">
                <small>カテゴリー：<a href="{% url 'blog:category_post' post.category.slug %}">{{ post.category.name }}</a></small></p>
            <p class="post-meta"><small>タグ:{% for tag in post.tags.all %}
                <a href="{% url 'blog:tag_post' tag.slug %}">{{tag.name}}</a>
                {% endfor %}
            </small></p>
                
        </div>
        {% endif %}
    </div>
   
{% endif %}
{% empty %}
<p>まだ投稿がありません</p>
{% endfor %}

blog/templates/blog/snippets/sidebar.html
<div class="card mb-3">
    <div class="card-header">
        カテゴリ
    </div>
    <ul class="list-group list-group-flush">
        {% for category in categories|dictsort:'id' %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'blog:category_post' category.slug %}" class="card-link">{{category.name}}</a>
            <span class="badge text-bg-primary">{{category.num_posts}}</span>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="card">
    <div class="card-header">
        タグ
    </div>
    <ul class="list-group list-group-flush">
        {% for tag in tags|dictsortreversed:'num_posts'|slice:'5' %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">{{tag.name}}</a>
            <span class="badge text-bg-primary">{{tag.num_posts}}</span>
        </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/tag_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% for tag in object_list %}
<li>{{tag.name}} <a href="{% url 'blog:tag_post' tag.slug %}">({{ tag.num_posts }})</a> </li>
{% empty %}
<li>カテゴリはありません。</li>
{% endfor %}

{% endblock %}

blog/templates/blog/tag_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>「#{{tag.name}}」の投稿一覧</h1>
    {% for post in object_list %}
    {% if user.is_authenticated or post.is_public %}
    <!-- Main Content-->
    <div class="card mb-3">
        {% if post.is_public %}
        <!-- <img src="..." class="card-img-top" alt="..."> -->
        <div class="card-body">
            <h5 class="card-title"><a href="{% url  'blog:post_detail' post.id %}">{{ post.title }}</a></h5>
            <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at|date}}</small></p>

            <p class="post-meta">
                Posted by
                <a href="/admin">{{user.username}}</a>
                on {{ post.published_at }}
            </p>
            <p class="post-meta">
                <small>カテゴリー：{{ post.category.name }}</small>
            </p>
            <p class="post-meta"><small>タグ:{% for tag in post.tags.all %}
                    {{tag.name}}
                    {% endfor %}
                </small></p>

        </div>
        {% endif %}
    </div>

    {% endif %}
    {% empty %}
    <p>まだ投稿がありません</p>
    {% endfor %}
    
    
    </div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MyGadgetBlog{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> 
    <!-- 自分のCSSを読みたい時はbootstrapの後に行う -->
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>

<body>
    {% include "base/navbar.html" %}

    {% block content %}
    {% endblock %}
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script> -->
</body>

</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ytaroのgadget</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>